/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const LojaIndexLazyImport = createFileRoute('/loja/')()
const AdminIndexLazyImport = createFileRoute('/admin/')()
const LojaRecuperarSenhaLazyImport = createFileRoute('/loja/recuperar-senha')()
const LojaEntrarLazyImport = createFileRoute('/loja/entrar')()
const AdminLoginLazyImport = createFileRoute('/admin/login')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LojaIndexLazyRoute = LojaIndexLazyImport.update({
  id: '/loja/',
  path: '/loja/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/loja/index.lazy').then((d) => d.Route))

const AdminIndexLazyRoute = AdminIndexLazyImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/index.lazy').then((d) => d.Route))

const LojaRecuperarSenhaLazyRoute = LojaRecuperarSenhaLazyImport.update({
  id: '/loja/recuperar-senha',
  path: '/loja/recuperar-senha',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/loja/recuperar-senha.lazy').then((d) => d.Route),
)

const LojaEntrarLazyRoute = LojaEntrarLazyImport.update({
  id: '/loja/entrar',
  path: '/loja/entrar',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/loja/entrar.lazy').then((d) => d.Route))

const AdminLoginLazyRoute = AdminLoginLazyImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/login.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/loja/entrar': {
      id: '/loja/entrar'
      path: '/loja/entrar'
      fullPath: '/loja/entrar'
      preLoaderRoute: typeof LojaEntrarLazyImport
      parentRoute: typeof rootRoute
    }
    '/loja/recuperar-senha': {
      id: '/loja/recuperar-senha'
      path: '/loja/recuperar-senha'
      fullPath: '/loja/recuperar-senha'
      preLoaderRoute: typeof LojaRecuperarSenhaLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/loja/': {
      id: '/loja/'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/admin/login': typeof AdminLoginLazyRoute
  '/loja/entrar': typeof LojaEntrarLazyRoute
  '/loja/recuperar-senha': typeof LojaRecuperarSenhaLazyRoute
  '/admin': typeof AdminIndexLazyRoute
  '/loja': typeof LojaIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/admin/login': typeof AdminLoginLazyRoute
  '/loja/entrar': typeof LojaEntrarLazyRoute
  '/loja/recuperar-senha': typeof LojaRecuperarSenhaLazyRoute
  '/admin': typeof AdminIndexLazyRoute
  '/loja': typeof LojaIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/admin/login': typeof AdminLoginLazyRoute
  '/loja/entrar': typeof LojaEntrarLazyRoute
  '/loja/recuperar-senha': typeof LojaRecuperarSenhaLazyRoute
  '/admin/': typeof AdminIndexLazyRoute
  '/loja/': typeof LojaIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/login'
    | '/loja/entrar'
    | '/loja/recuperar-senha'
    | '/admin'
    | '/loja'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/loja/entrar'
    | '/loja/recuperar-senha'
    | '/admin'
    | '/loja'
  id:
    | '__root__'
    | '/'
    | '/admin/login'
    | '/loja/entrar'
    | '/loja/recuperar-senha'
    | '/admin/'
    | '/loja/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AdminLoginLazyRoute: typeof AdminLoginLazyRoute
  LojaEntrarLazyRoute: typeof LojaEntrarLazyRoute
  LojaRecuperarSenhaLazyRoute: typeof LojaRecuperarSenhaLazyRoute
  AdminIndexLazyRoute: typeof AdminIndexLazyRoute
  LojaIndexLazyRoute: typeof LojaIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AdminLoginLazyRoute: AdminLoginLazyRoute,
  LojaEntrarLazyRoute: LojaEntrarLazyRoute,
  LojaRecuperarSenhaLazyRoute: LojaRecuperarSenhaLazyRoute,
  AdminIndexLazyRoute: AdminIndexLazyRoute,
  LojaIndexLazyRoute: LojaIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin/login",
        "/loja/entrar",
        "/loja/recuperar-senha",
        "/admin/",
        "/loja/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/admin/login": {
      "filePath": "admin/login.lazy.tsx"
    },
    "/loja/entrar": {
      "filePath": "loja/entrar.lazy.tsx"
    },
    "/loja/recuperar-senha": {
      "filePath": "loja/recuperar-senha.lazy.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.lazy.tsx"
    },
    "/loja/": {
      "filePath": "loja/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
