/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminLoginImport } from './routes/admin/login'
import { Route as AdminAuthImport } from './routes/admin/_auth'

// Create Virtual Routes

const AdminImport = createFileRoute('/admin')()
const IndexLazyImport = createFileRoute('/')()
const LojaIndexLazyImport = createFileRoute('/loja/')()
const LojaRecuperarSenhaLazyImport = createFileRoute('/loja/recuperar-senha')()
const LojaEntrarLazyImport = createFileRoute('/loja/entrar')()
const AdminAuthIndexLazyImport = createFileRoute('/admin/_auth/')()

// Create/Update Routes

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LojaIndexLazyRoute = LojaIndexLazyImport.update({
  id: '/loja/',
  path: '/loja/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/loja/index.lazy').then((d) => d.Route))

const LojaRecuperarSenhaLazyRoute = LojaRecuperarSenhaLazyImport.update({
  id: '/loja/recuperar-senha',
  path: '/loja/recuperar-senha',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/loja/recuperar-senha.lazy').then((d) => d.Route),
)

const LojaEntrarLazyRoute = LojaEntrarLazyImport.update({
  id: '/loja/entrar',
  path: '/loja/entrar',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/loja/entrar.lazy').then((d) => d.Route))

const AdminLoginRoute = AdminLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)

const AdminAuthRoute = AdminAuthImport.update({
  id: '/_auth',
  getParentRoute: () => AdminRoute,
} as any)

const AdminAuthIndexLazyRoute = AdminAuthIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthRoute,
} as any).lazy(() =>
  import('./routes/admin/_auth.index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/admin/_auth': {
      id: '/admin/_auth'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginImport
      parentRoute: typeof AdminImport
    }
    '/loja/entrar': {
      id: '/loja/entrar'
      path: '/loja/entrar'
      fullPath: '/loja/entrar'
      preLoaderRoute: typeof LojaEntrarLazyImport
      parentRoute: typeof rootRoute
    }
    '/loja/recuperar-senha': {
      id: '/loja/recuperar-senha'
      path: '/loja/recuperar-senha'
      fullPath: '/loja/recuperar-senha'
      preLoaderRoute: typeof LojaRecuperarSenhaLazyImport
      parentRoute: typeof rootRoute
    }
    '/loja/': {
      id: '/loja/'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/_auth/': {
      id: '/admin/_auth/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthIndexLazyImport
      parentRoute: typeof AdminAuthImport
    }
  }
}

// Create and export the route tree

interface AdminAuthRouteChildren {
  AdminAuthIndexLazyRoute: typeof AdminAuthIndexLazyRoute
}

const AdminAuthRouteChildren: AdminAuthRouteChildren = {
  AdminAuthIndexLazyRoute: AdminAuthIndexLazyRoute,
}

const AdminAuthRouteWithChildren = AdminAuthRoute._addFileChildren(
  AdminAuthRouteChildren,
)

interface AdminRouteChildren {
  AdminAuthRoute: typeof AdminAuthRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuthRoute: AdminAuthRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminAuthRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/loja/entrar': typeof LojaEntrarLazyRoute
  '/loja/recuperar-senha': typeof LojaRecuperarSenhaLazyRoute
  '/loja': typeof LojaIndexLazyRoute
  '/admin/': typeof AdminAuthIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminAuthIndexLazyRoute
  '/admin/login': typeof AdminLoginRoute
  '/loja/entrar': typeof LojaEntrarLazyRoute
  '/loja/recuperar-senha': typeof LojaRecuperarSenhaLazyRoute
  '/loja': typeof LojaIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/_auth': typeof AdminAuthRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/loja/entrar': typeof LojaEntrarLazyRoute
  '/loja/recuperar-senha': typeof LojaRecuperarSenhaLazyRoute
  '/loja/': typeof LojaIndexLazyRoute
  '/admin/_auth/': typeof AdminAuthIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/loja/entrar'
    | '/loja/recuperar-senha'
    | '/loja'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/loja/entrar'
    | '/loja/recuperar-senha'
    | '/loja'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/_auth'
    | '/admin/login'
    | '/loja/entrar'
    | '/loja/recuperar-senha'
    | '/loja/'
    | '/admin/_auth/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AdminRoute: typeof AdminRouteWithChildren
  LojaEntrarLazyRoute: typeof LojaEntrarLazyRoute
  LojaRecuperarSenhaLazyRoute: typeof LojaRecuperarSenhaLazyRoute
  LojaIndexLazyRoute: typeof LojaIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AdminRoute: AdminRouteWithChildren,
  LojaEntrarLazyRoute: LojaEntrarLazyRoute,
  LojaRecuperarSenhaLazyRoute: LojaRecuperarSenhaLazyRoute,
  LojaIndexLazyRoute: LojaIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/loja/entrar",
        "/loja/recuperar-senha",
        "/loja/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/admin": {
      "filePath": "admin",
      "children": [
        "/admin/_auth",
        "/admin/login"
      ]
    },
    "/admin/_auth": {
      "filePath": "admin/_auth.tsx",
      "parent": "/admin",
      "children": [
        "/admin/_auth/"
      ]
    },
    "/admin/login": {
      "filePath": "admin/login.tsx",
      "parent": "/admin"
    },
    "/loja/entrar": {
      "filePath": "loja/entrar.lazy.tsx"
    },
    "/loja/recuperar-senha": {
      "filePath": "loja/recuperar-senha.lazy.tsx"
    },
    "/loja/": {
      "filePath": "loja/index.lazy.tsx"
    },
    "/admin/_auth/": {
      "filePath": "admin/_auth.index.lazy.tsx",
      "parent": "/admin/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
